vertex_ai_featurestore/main.tf
https://cloud.google.com/vertex-ai/docs/featurestore/managing-featurestores
```release-note:none
```
=> Prepared vertex_ai_featurestore for inclusion in C.G.C. documentation

build/int.cloudbuild.yaml, cloud_run_service_custom_domain_mapping/test.yaml, regional_external_http_load_balancer/main.tf, test/integration/sample_test.go, test/setup/fixtures.tf, test/setup/iam.tf, test/setup/main.tf, test/setup/outputs.tf
This introduces parallelization when running tests in CI. Sample tests are grouped in to n test groups based [on num projects](https://github.com/terraform-google-modules/terraform-docs-samples/blob/60fbf0ed06e40b5d7e9d3ef3bc0cf069caddf64a/test/setup/main.tf#L18-L21) in setup. I added 4 projects to start with and has resulted in a test time reduction from ~62.5%  (from 4h to 1:30h). 
Test grouping is dynamic and increasing number of projects in the future to reduce time would be a trivial change.
=> chore: parallel tests

regional_external_http_load_balancer/main.tf
Dear team,
In the startup script defined in the creation of an instance template, the name of the instance is not getting captured in the variable `host_name`:
Updating the startup script (for the VMs) for different load balancers to remove `sudo` before the variable `vm_hostname`. This allows the name of the instance to get captured correctly:
http://b/246878070
=> removing sudo before the name of the vm_hostname variable

external_http_lb_mig_backend/main.tf
In instance template, remove "sudo" in vm_hostname startup script as using sudo was not setting vm_hostname variable during startup. No need to use "sudo" while setting variable.
=> remove sudo in vm_hostname vm startup script

shared_vpc_http_ilb_with_mig_backend/main.tf
Updating main.tf as per https://cloud.google.com/load-balancing/docs/proxy-only-subnets#proxy_only_subnet_create suggests recommendation
> For internal HTTP(S) load balancers, --purpose=REGIONAL_MANAGED_PROXY is the preferred setting even though --purpose=INTERNAL_HTTPS_LOAD_BALANCER also works.
=> Minor change in Shared VPC LB

cloud_run_service_pubsub/main.tf
This PR will replace the name of a cloud run service to remove unallowed `_` character:
Context:
```
│ Error: Error creating Service: googleapi: Error 400: metadata.name: Resource name must use only lowercase letters, numbers and '-'. Must begin with a letter and cannot end with a '-'. Maximum length is 63 characters.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "Resource name must use only lowercase letters, numbers and '-'. Must begin with a letter and cannot end with a '-'. Maximum length is 63 characters.",
│         "field": "metadata.name"
│       }
│     ]
│   }
│ ]
```
=> remove `_` from run service name

cloudfunctions2_basic_auditlogs/main.tf
In the logs, the hard-coded bucket name shows up as an error:
```
TestSamples/1/cloudfunctions2_basic_auditlogs 2022-09-26T20:50:04Z command.go:185: ╵
TestSamples/1/cloudfunctions2_basic_auditlogs 2022-09-26T20:50:04Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
│ Error: googleapi: Error 409: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again., conflict
│ 
│   with google_storage_bucket.audit-log-bucket,
│   on main.tf line 31, in resource "google_storage_bucket" "audit-log-bucket":
│   31: resource "google_storage_bucket" "audit-log-bucket" {
│ 
╵}
apply.go:34: 
Error Trace:	apply.go:34
terraform.go:398
terraform.go:408 …
```
=> Changed bucket name to use a bucket_prefix

test/setup/main.tf
Sometimes tests are flaky for vertex AI with API enablement eventual consistency. This adds the API to test setup which should help. If it continues to be flaky, we can add this to retry https://github.com/terraform-google-modules/terraform-docs-samples/blob/f7e01ec4a76d6ea38ce0e51ea738a0a5c0546415/test/integration/sample_test.go#L27-L31
=> chore: add notebooks.googleapis.com to test setup

test/integration/sample_test.go
Still see a few flakes for service activation after https://github.com/terraform-google-modules/terraform-docs-samples/pull/180, so we retry these now. Also added `*does not have storage.objects.get access` to retry GCS IAM.
=> chore: retry service activation, IAM

privateca_quickstart/main.tf
Example appears here:
https://cloud.google.com/certificate-authority-service/docs/using-terraform
=> privateca_quickstart: Removed read-only attribute, enabled necessary API, fixed faulty attribute reference

compute_run_shutdown_scripts/main.tf, compute_run_shutdown_scripts/shutdown-script.sh
Intended for this page:
https://cloud.google.com/compute/docs/shutdownscript
=> Added example for Compute VM with shutdown script

cloudfunctions2_basic/main.tf, cloudfunctions2_basic_auditlogs/main.tf, cloudfunctions2_basic_gcs/main.tf, cloudfunctions2_full/main.tf
This will add the minimum required version in order to make potential errors more obvious:
Before:
```bash
Error: Invalid resource type
on main.tf line 27, in resource "google_cloudfunctions2_function" "function":
27: resource "google_cloudfunctions2_function" "function" {
The provider hashicorp/google does not support resource type "google_cloudfunctions2_function". Did you mean "google_cloudfunctions_function"?
```
After:
```bash
Error: Inconsistent dependency lock file
The following dependency selections recorded in the lock file are inconsistent with the current configuration:
- provider registry.terraform.io/hashicorp/google: locked version selection 4.32.0 doesn't match the updated version constraints ">= 4.34.0"
To update the locked dependency selections to match a changed …
```
=> Add provider requirement to functions v2 to make error message more obvious

cloud_run_service_image_processing/main.tf, cloud_run_service_pubsub/main.tf
This PR adds sample for [Processing images from Cloud Storage tutorial](https://cloud.google.com/run/docs/tutorials/image-processing)
This tutorial relies on resources deployed in [`cloud_run_service_pubsub`.](https://github.com/terraform-google-modules/terraform-docs-samples/tree/main/cloud_run_service_pubsub) Those resources are contained in the `cloudrun_service_existing_pubsub` region tag.
This PR also updates the name of a pubsub topic for consistency.
=> feat(cloudrun): Add Image Processing sample

compute_add_persistent_disk/main.tf
Planning to include on this page:
https://cloud.google.com/compute/docs/disks/add-persistent-disk
=> Added example for adding a disk to a VM

compute_add_persistent_disk/main.tf
In the not-too-distant future, we'll want to nudge users toward the new hyperdisk family (newer generation of disks), so we might want to remove this comment from the sample to avoid the debt.
=> Removed comment to avoid technical debt

privateca_quickstart/main.tf
This will allow customers to cleanup testing resources via `terraform destroy` directly.
Without this changes, cleanup CA resources require manual procedures listed in https://cloud.google.com/certificate-authority-service/docs/using-terraform#clean_up
=> Disable deletion related safe checks on CA resources for easier cleanup.

compute/global_external_address/main.tf
Planning to update this page:
https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address
Fixes b/262263842
=> Added external VM address example

compute/external_address/main.tf
using on this page:
https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address
=> Fixed directory name and region tag

dns_managed_zone_with_dnssec/main.tf, dns_managed_zone_with_dnssec/test.yaml
Add cloud dns example for DNSSEC
Reference: https://cloud.google.com/dns/docs/dnssec-config#gcloud_1
=> chore(dns): example cloud dns example with dnssec

dns_managed_zone_with_wildcard_certificate/main.tf, network_management_connectivity_test_addresses/main.tf
As per the latest docs, ip addresses used in Connectivity tests must be already in use by other resources like Compute VM.
=> Bugfix - Connectivity Tests

iam_create_deny_policy/main.tf, iam_create_deny_policy/test.yaml
Adding TF Snippet at https://cloud.google.com/iam/docs/deny-access#create-deny-policy
For more details, please check http://b/233721480
Request for reviewers: If allowed, please update path from `iam_create_deny_policy/main.tf` to `iam/iam_create_deny_policy/main.tf` (i.e. Using separate folder for IAM snippets) or advice as such.
=> Add IAM Deny policy snippet

certificate_manager/google_managed_lb_auth/main.tf
Intending to add "Terraform"-equivalent tabs to this page:
https://cloud.google.com/certificate-manager/docs/deploy-google-managed-lb-auth
=> TF for Certificate Manager: /certificate-manager/docs/deploy-google-managed-lb-auth

cloud_run_jobs_task_timeout_create/main.tf
cloud_run_jobs_task_timeout_create sample sets `timeout` to `3.5s`. However looks like this field is mutated serverside into `3.500s` causing TF to report a diff. This PR sets the timeout to `3.500s` to hopefully prevent this diff.
=> fix cloud_run_jobs_task_timeout_create diff

iam_create_deny_policy/main.tf
In the example, you're not creating a deny policy "for the service account"; the deny policy is attached to the project, not the service account.
=> fix: clarify comments in IAM deny policy example

migrate-csv.sh
This PR adds the following to the `migrate-csv.sh` script:
- formatting
- comments
- create subdirectories for non-existing destinations
=> add to migration script

migrate-csv.sh
This PR will add the following to `migrate-csv.sh`:
- allow script to accept csv with header (default in export from Sheets)
- allow script to accept csv with missing new line at end of file (default in export from Sheets)
- formatted bash
- add a continue prompt after preview of changes
=> Updates to migration script

vertex_ai_featurestore_entitytype/main.tf
https://cloud.google.com/vertex-ai/docs/featurestore/managing-entity-types
```release-note:none
```
=> Prepare vertex_ai_featurestore_entitytype for inclusion in C.G.C. documentation

vertex_ai/vertex_ai_endpoint/main.tf
https://cloud.google.com/vertex-ai/docs/predictions/using-private-endpoints
=> Prepared vertex_ai_endpoint for inclusion in CFC documentation

test/integration/sample_test.go
This skips the default diff verification in tests and replaces it with a noop stub.
=> chore: skip default diff verify

vertex_ai/tensorboard/main.tf
https://cloud.google.com/vertex-ai/docs/experiments/tensorboard-overview
=> Prepared vertex_ai_tensorboard for inclusion in C.G.C. documentation

test/setup/main.tf
Added aiplatform.googleapis.com to the activate_apis list to enable Vertex AI API for integration tests so individual samples won't need to enable the API by themselves.
=> chore: enable Vertex AI API for integration tests 

vertex_ai/index/main.tf
Randomize the cloud storage bucket name for sample `vertex_ai/index`.
=> fix: randomize cloud storage bucket name

storage/static_website/main.tf
Fixes #bug-243796252
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/storage/docs/hosting-static-website
Reason:
**Review**
=> Fixing storage static website example.

cloud_sql/instance_iam_condition/main.tf
Fixes # b/262072140
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/sql/docs/mysql/iam-conditions 
Reason:
**Review**
=> Fixed project id attribute in Cloud SQL IAM sample

vertex_ai/dataset/main.tf, vertex_ai/dataset/test.yaml, vertex_ai/endpoint/main.tf, vertex_ai/featurestore/main.tf, vertex_ai/featurestore_entitytype/main.tf, vertex_ai/index/main.tf, vertex_ai/managed_notebooks_runtime/main.tf, vertex_ai/metadata_store/main.tf, vertex_ai/tensorboard/main.tf, vertex_ai/user_managed_notebooks_instance/main.tf
Fixes #279425203
Updated region tags for Vertex AI samples to support the sample browser.
Cleaned up samples to make samples standalone.
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
=> chore: Updated region tags to support the sample browser

compute/run_shutdown_scripts/main.tf
Adding new region tag as first step. On completion of cl/536210605, region tag with spell issue will be cleared. Thanks.
**Readiness**
**Style**
**Testing**
Location(s): cl/536210605
Reason:
**Review**
=> chore: fix spell check in compute region tag

storage/make_data_public/main.tf
**Readiness**
**Style**
**Testing**
Location(s):https://cloud.google.com/storage/docs/access-control/making-data-public 
Reason:
**Review**
=> refactor: No need for google-beta

storage/flask_google_cloud_quickstart/main.tf, storage/flask_google_cloud_quickstart/test.yaml
Fixes # b/284014407
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/docs/terraform/resource-management/store-state
Reason:
**Review**
=> feat(Cloud Storage): Add bucket encryption sample

run/access_control/main.tf, run/add_tag/main.tf, run/connect_cloud_sql/main.tf, run/custom_domain_mapping/main.tf, run/deploy_tag/main.tf, run/healthchecks_liveness_probe_grpc/main.tf, run/healthchecks_liveness_probe_http/main.tf, run/healthchecks_startup_probe_http/main.tf, run/healthchecks_startup_probe_tcp/main.tf, run/identity/main.tf, run/image_processing/main.tf, run/ingress/main.tf, run/interservice/main.tf, run/multiple_regions/main.tf, run/noauth/main.tf, run/pubsub/main.tf, run/remove_tag/main.tf, run/scheduled/main.tf, run/secure_services/main.tf, run/static_outbound/main.tf, run/system_packages/main.tf, run/tasks/main.tf, run/traffic_gradual_rollout/main.tf, run/traffic_latest_revision/main.tf, run/traffic_rollback/main.tf, run/traffic_split/main.tf, run/traffic_split_tag/main.tf, run/vpc_access_connector/main.tf
Updates most Cloud Run samples to use google_cloud_run_v2_services.
go/tf-cloudrun_v2-update-plan
(after this PR, some references remain, to be handled separately)
**Readiness**
**Style**
**Testing**
Location(s): many
Reason:
**Review**
=> feat: update Cloud Run services to google_cloud_run_v2_service

run/connect_cloud_sql/main.tf, run/multiple_regions/main.tf
This PR removes the use of `var.domain` from the multiple_regions sample, per our [published style guide](https://googlecloudplatform.github.io/samples-style-guide/#no-global-variables).
Variable resource block will remain until doc page is updated with its removal: https://cloud.google.com/run/docs/multiple-regions#:~:text=Replace%20example.com%20with%20your%20domain%20name%3A
=> chore(run): Replace `var.domain` with `example.com` (1 of 2)

run/multiple_regions/main.tf
This PR removes the use of variables from the multiple_regions run sample  per our [published style guide](https://googlecloudplatform.github.io/samples-style-guide/#no-global-variables).
- It replaces the `run_regions` variable with a local value
- removes the `domain_name` variable as it is no longer referenced in [the documentation](https://cloud.google.com/run/docs/multiple-regions#:~:text=Replace%20example.com%20with%20your%20domain%20name%3A)
This PR is a followup to #468
=> chore(run): Remove variables from `multiple_regions` sample (2 of 2)

bigquery/bigquery_create_object_table/main.tf, test/setup/main.tf
https://cloud.google.com/bigquery/docs/object-tables
**Readiness**
**Style**
**Testing**
Location(s):
https://cloud.google.com/bigquery/docs/object-tables#create-object-table
Reason:
**Review**
=> add: `bigquery_create_object_table`

compute/reservation/create_local/main.tf
Adding file to create single-project reservations by specifying properties directly.
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
=> feat(compute): Add example to create a single-project reservation

run/cloud_run_configuration_cpu_allocation/main.tf, run/cloud_run_configuration_description/main.tf
Addresses b/290538179
Adds examples for Cloud Run description, cpu allocation
Location(s):
* https://cloud.devsite.corp.google.com/run/docs/configuring/cpu-allocation
* https://cloud.devsite.corp.google.com/run/docs/configuring/description 
Reason:
**Review**
=> feat: add cpu allocation, description samples for Cloud Run

run/cloud_run_configuration_concurrency/main.tf, run/cloud_run_configuration_containers/main.tf, run/cloud_run_configuration_cpu/main.tf, run/cloud_run_configuration_environment_variables/main.tf, run/cloud_run_configuration_http2/main.tf, run/cloud_run_configuration_labels/main.tf, run/cloud_run_configuration_max_instances/main.tf, run/cloud_run_configuration_memory_limits/main.tf, run/cloud_run_configuration_min_instances/main.tf, run/cloud_run_configuration_request_timeout/main.tf, run/healthchecks_liveness_probe_grpc/main.tf, run/healthchecks_liveness_probe_http/main.tf, run/healthchecks_startup_probe_http/main.tf, run/healthchecks_startup_probe_tcp/main.tf
Assists b/290538179
Pairs with cl/557303797
Updates google_cloud_run_service to google_cloud_run_v2_service
**Readiness**
**Style**
**Testing**
**Review**
=> fix: update Cloud Run configurations to v2 resource

bigquery/biglake/bigquery_create_partitioned_biglake_table/main.tf
Missing field may mislead users. go/terrap/issues/15804 
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/bigquery/docs/create-cloud-storage-table-biglake#create-biglake-partitioned-data
Reason:
**Review**
=> fix(bigquery): Add missing connection_id attribute

cloud_sql/instance_cmek/test.yaml, cloud_sql/mysql_instance_cmek/test.yaml, cloud_sql/postgres_instance_cmek/test.yaml, cloud_sql/sqlserver_instance_cmek/test.yaml
This PR will skip integration tests for cloud sql samples that use the `google_kms_key_ring` resource due to it causing integration tests to fail.
Fixes #504
=> fix(tests): skip samples with keyring resource

run/connect_cloud_sql/main.tf, run/secret_manager/main.tf
With v5.0.0 of the Google provider, the parameter `automatic` for the [`google_secret_manager_secret` resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret) has been deprecated in favor of the `auto` parameter. This PR replaces its use in 2 Cloud Run samples
=> fix(run): replace `automatic` with `auto` param in secrets resources

build/int.cloudbuild.yaml, build/lint.cloudbuild.yaml
This PR will add an additional step to `int.cloudbuild.yaml` that will remove unaltered directories from the included int tests.
Based on [Running Cloud Build with Pull Request context](https://glasnt.com/blog/cloud-build-pull-request-context/)
=> fix(tests): add directory prune to int build config

build/int.cloudbuild.yaml
Reverts terraform-google-modules/terraform-docs-samples#508
With this change integration test unintentionally skip all directories instead of unchanged ones. Back to the drawing board.
=> Revert "fix(tests): add directory prune to int build config"

network_connectivity/service_connectivity_automation/service_connection_policies/main.tf, test/setup/main.tf
I'm creating this as a draft PR because I haven't been able to run the tests at https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#set-up-the-test-environment. I was able to try `terraform apply` and verify that it created the right resources in my test project. 
Fixes #302014019
**Readiness**
**Style**
**Testing**
I have not been able to complete the tests below. After following the steps in the guide, `make -s docker_test_sample SAMPLE=networkconnectivity_create_service_connection_policy` ends with
``` …
```
=> feat(networkconnectivity): Add samples for creating a service-connection-policy

bigquery/biglake/bigquery_create_unpartitioned_biglake_table/main.tf, compute/add_persistent_disk/main.tf, compute/mig_stateful_disk_basic/main.tf, vertex_ai/endpoint/main.tf
Fix spell mistakes
Fixes: b/314735566
=> docs: fix spell issues

vertex_ai/metadata_store/main.tf, vertex_ai/metadata_store_cmek/main.tf
Fixes b/317093604
- Update the basic metadata store sample
- Add a new sample for creating metadata store with cmek
Doc page: https://cloud.google.com/vertex-ai/docs/ml-metadata/configure
=> feat: update/add new samples for metadata store

run/healthchecks_startup_probe_grpc/main.tf, run/healthchecks_startup_probe_grpc/test.yaml
Fixes b/315103435
This sample is untestable using the hello container, because it does not implement grpc healthchecks. (The grpc liveness probe sample does not override the startup probe, so it successfully deploys. Since this is a startup probe, the deployment will fail, so it is untestable using the default image.)
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/run/docs/configuring/healthchecks#grpc-startup-probe
=> feat: add sample for grpc startup probe

cloud_sql/sqlserver_instance_psc/main.tf
Added documentation for managing SQL server psc connectivity on Cloud SQL instances.
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
=> feat(cloud_sql): Add cloud sql psc connectivity SQL server sample

test/setup/main.tf
Underlying logic for random_project_id_length also uses `random_string` for a larger collusion domain so hopefully reduces collisions
=> chore: switch to longer rand prefix for int test projects

vertex_ai/workbench/main.tf
Fixes b/319246086
Add a Workbench basic GPU instance code sample.
https://cloud.google.com/vertex-ai/docs/workbench/instances/create
=> feat: prepare workbench snippet for inclusion in CGC documentation

vertex_ai/api/main.tf
Fixes b/321690958
Add sample for enabling Vertex AI API for documentation.
Docs: https://cloud.google.com/vertex-ai/docs/start/cloud-environment#enable_vertexai_apis
=> feat: add enabling vertex ai api sample for documentation

cloud_sql/mysql_instance_ssl_cert/main.tf
We have introduced `ssl_mode` to MySQL instances. Thus its SSL example should be updated too.
Fixes #313530521
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/sql/docs/mysql/configure-ssl-instance#terraform
Reason:
**Review**
=> docs: Introduce the ssl_mode into the MySQL SSL example

compute/pic_disks/main.tf
Fixes b/216660539
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/compute/docs/instance-groups/configuring-stateful-disks-in-migs#adding_existing_stateful_disks_to_new_vms_in_a_mig
Reason:
**Review**
=> feat: Add example for MIG with Stateful disk in PIC

compute/instance_template_with_gpu/main.tf
Fixes b/320434395
**Readiness**
**Style**
**Testing**
Location(s):
- https://cloud.google.com/compute/docs/samples/compute-template-gpu
- https://cloud.google.com/compute/docs/instance-templates/create-instance-templates
Reason:
**Review**
=> fix: Removing optional flags from the command to create an instance template for GPU VMs

workflows/cloud_run_job/test.yaml
Fixes #605, #606
This test correctly identifies the image that is created in the tutorial, but that image is per-project, and not created in tests. 
Simplest way to prevent perioidic testing issues is to disable this sample from being tested. 
(Alternative is to edit the workflow image to be `hello`, which will require user editing, but as the workflow is only provisioned and not executed, this would be successful as far as `terraform apply` is concerned.)
**Readiness**
**Style**
=> fix: prevent application of workflows/cloud_run_job

gke/standard/regional/multi-zone/main.tf, gke/standard/regional/single-zone/main.tf, gke/standard/zonal/multi-zone/main.tf, gke/standard/zonal/single-zone/main.tf
Adds the following samples:
- GKE Standard Zonal
- Single-Zone
- Multi-Zone
- GKE Standard Regional
- Single-Zone
- Multi-Zone
**Readiness**
**Style**
**Testing**
Location(s):
- https://cloud.google.com/kubernetes-engine/docs/how-to/creating-a-zonal-cluster
- https://cloud.google.com/kubernetes-engine/docs/how-to/creating-a-regional-cluster
Reason:
**Review**
=> feat: add gke standard samples

compute/firewall_rule_for_health_check/main.tf, compute/health_check/main.tf, compute/zonal_mig_health_check/main.tf
Fixes #216660554
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/compute/docs/instance-groups/autohealing-instances-in-migs
Reason:
**Review**
=> fix: Fix inconsistent quotes in mig hc examples

gke/autopilot/labels/main.tf, gke/standard/regional/labels/main.tf
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/docs/how-to/creating-managing-labels
Reason:
**Review**
=> feat(GKE): add labels examples

Makefile
enable `make_docker_lint` to run tf validate in parallel
=> chore: enable local parallel lint

gke/autopilot/tag/main.tf
- add GKE cluster into snippet region tag
**Readiness**
**Style**
**Testing**
Location(s): (existing sample)
Reason:
**Review**
=> fix: add GKE cluster into snippet tag

gke/quickstart/autopilot/app.tf
Back porting improvement from https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/gke/standard/regional/loadbalancer/main.tf#L103
**Readiness**
**Style**
**Testing**
Location(s): (existing sample)
Reason:
**Review**
=> fix: enable run_as_non_root

build/int.cloudbuild.yaml
The trigger `terraform-docs-samples-periodic-int-trigger` has been failing due to timeout. 
This PR increases the timeout for this config from 4 hours to 6 hours. 
Noting that this configuration is run for both PR tests and nightly periodic tests, so the timeout applies for both.
=> chore: increase periodic test timeout to 6 hours

gke/autopilot/reservation/main.tf, gke/autopilot/reservation/test.yaml, gke/standard/zonal/reservation/main.tf
add GKE reservation samples
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/docs/how-to/consuming-reservations
Reason:
**Review**
=> feat(GKE): add reservation samples

gke/standard/zonal/secondary-boot-disk/main.tf
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/docs/how-to/data-container-image-preloading
Reason:
**Review**
=> feat(GKE): Add secondary boot disk sample for preloaded data

compute/zonal_mig_standby_policy/main.tf
Fixes #335382497
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/compute/docs/instance-groups/accelerate-mig-scale-out-with-standby-pools#edit_the_standby_policy_in_a_mig
Reason:
**Review**
=> feat(compute): Added example for mig standby policy

.github/workflows/lint.yaml
Reverts terraform-google-modules/terraform-docs-samples#672
Recently, linting checks have been erroring with disk space errors: `No space left on device`. This is blocking PRs from being merged. E.g. https://github.com/terraform-google-modules/terraform-docs-samples/actions/runs/9581832081/attempts/3?pr=696
The change in #672 introduced using a variable that through cft/developer-tools uses `parallel`, but also changed the value for TF_PLUGIN_CACHE_DIR, a variable that configures [plugin caching](https://developer.hashicorp.com/terraform/cli/config/config-file#provider-plugin-cache), from the cft/developer-tools default, to not using one. 
Since linting is occurring at a per sample level, without the cache, the provider is being downloaded to the local `.terraform/` directory, at a size …
=> Revert "chore(CI): parallel lint"

.github/CODEOWNERS, managedkafka/managedkafka_create_cluster/main.tf, managedkafka/managedkafka_create_topic/main.tf, test/setup/main.tf
Fixes https://b.corp.google.com/issues/343411931
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/managed-kafka/docs
Reason:
**Review**
=> docs: Add Managed Kafka terraform samples for Clusters and Topics

storage/remote_terraform_backend_template/README.md, storage/remote_terraform_backend_template/main.tf
Use a variable to set the force_destroy attribute of the Cloud Storage bucket to store the Terraform state. This is helpful to simplify the related tutorial because we can ask users to adjust the value of the variable, instead of asking them to modify the source code.
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
=> feat: make force_destroy configurable

storage/remote_terraform_backend_template/README.md, storage/remote_terraform_backend_template/main.tf
This reverts commit da45049037192709f185cd4e425acbfaa768d43c.
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
=> chore: revert "feat: make force_destroy configurable (#703)"

compute/basic_vm/main.tf, compute/packet_mirroring_full/main.tf, lb/external_http_lb_mig_backend_custom_header/main.tf, lb/external_ssl_proxy_lb_mig_backend/main.tf, lb/external_ssl_proxy_lb_mig_backend_custom_header/main.tf, lb/external_tcp_proxy_lb_mig_backend/main.tf, lb/external_tcp_proxy_lb_mig_backend_custom_header/main.tf, lb/int_https_lb_https_redirect/main.tf, lb/internal_http_lb_with_mig_backend/main.tf, lb/internal_tcp_udp_lb_with_mig_backend/main.tf, lb/regional_external_http_load_balancer/main.tf, lb/shared_vpc_http_ilb_with_mig_backend/main.tf, lb/shared_vpc_http_ilb_with_mig_backend_basic_example/main.tf, lb/shared_vpc_http_ilb_with_mig_backend_cross_reference_example/main.tf, lb/shared_vpc_https_ilb_with_mig_backend_basic_example/main.tf, lb/shared_vpc_https_ilb_with_mig_backend_cross_reference_example/main.tf
* On June 30, `debian-10` reached end-of-life. See [source](https://www.debian.org/News/2024/20240615#:~:text=The%20Debian%20Long%20Term%20Support,security%20updates%20for%20Debian%2010.).
* We will need to update Terraform samples that use `debian-10` to use `debian-12`.
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
=> fix: Update debian-10 to debian-12

gke/standard/regional/binary-authorization/main.tf
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/binary-authorization/docs/creating-cluster
Reason:
**Review**
=> feat(GKE): add binary-authorization enforce sample

gke/standard/regional/ray/main.tf
Add sample for enabling Ray Operator addon
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/docs/add-on/ray-on-gke/how-to/enable-ray-on-gke
Reason:
**Review**
=> feat(GKE): add sample for using Ray Operator addon

cloud_sql/instance_ssl_cert/main.tf, cloud_sql/mysql_instance_ssl_cert/main.tf, cloud_sql/postgres_instance_ssl_cert/main.tf, cloud_sql/sqlserver_instance_ssl_cert/main.tf
Migrate from `require_ssl` to `ssl_mode` for: https://github.com/hashicorp/terraform-provider-google/releases/tag/v6.0.1 
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
=> fix(cloud_sql): update to ssl_mode

bigquery/bigquery_tags_tag_key/main.tf
Fixes #353964666
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/resource-manager/docs/tags/tags-creating-and-managing#creating_tag
Reason:
**Review**
=> feat(bigquery): Add example for creating a tag key

run/add_tag/main.tf, run/custom_domain_mapping/main.tf, run/pubsub/main.tf, run/remove_tag/main.tf, run/traffic_gradual_rollout/main.tf, run/traffic_latest_revision/main.tf, run/traffic_rollback/main.tf, run/traffic_split/main.tf, run/traffic_split_tag/main.tf
Add `deletion_protection = false` for `google_cloud_run_v2_service` for TPGv6
In partial resolution of https://github.com/terraform-google-modules/terraform-docs-samples/issues/740
=> fix(cloud_run): add deletion_protection

.github/CODEOWNERS
Fixes b/368475360 and cleans up unused teams/redundant entries.
As part of this, there's a new row for `/*`, this is a way to give CODEOWNERS authority to root files without the entire repo: the cloud-samples-infra team is not scoped for reviewing terraform sample changes.
GitHub is now marking this change as invalid because the new team needs to be added as a repo admin. Requesting a reviewer from terraform-samples-git-admins take care of that.
**Readiness**
**Style**
**Testing**
Location(s):
Reason: …
=> chore(CODEOWNERS): Remove unused teams and add cloud-samples-infra

gke/quickstart/multitenant/main.tf
add `gke_enterprise_policycontroller_fleet` tag
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/enterprise/policy-controller/docs/how-to/installing-policy-controller
Reason:
**Review**
=> feat(gke): add poco tag

compute/rmig_instance_flexibility_policy/main.tf
Fixes #333070003
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
=> feat(compute): add terraform sample for instanceflexibilitypolicy of rmig

build/int.cloudbuild.yaml
- completely remove unchanged base folders
- ignore `test.yaml` when preserving leaf folders
=> chore(CI): completely remove unchanged base folders

application_integration/provision_region/main.tf
Changes are inline with https://github.com/GoogleCloudPlatform/magic-modules/pull/12418/files#
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
=> fix: added fix to use basename of kms config

build/int.cloudbuild.yaml
The test pruner could accidentally delete `_changed_folders`, which impacts the sub-folder pruning.
Tested using: https://github.com/terraform-google-modules/terraform-docs-samples/pull/788
=> chore(CI): fix test pruner

eventarc/basic_pubsub/main.tf
Per b/355941670
Create new Terraform quickstart for Eventarc
**Readiness**
- [ x] Yes, **merge** this PR after it is approved
**Style**
- [ x] My sample follows the rules described for Terraform in the [Effective Samples style guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [ x] My sample follows the other requirements and best practices in the [Contributing
**Testing**
- [ x] I have performed tests described in the [Contributing guide](https://github.com/terraform-google-modules/terraform-docs-samples/bl …
=> docs: Create main.tf to support quickstart in Eventarc docset

eventarc/workflows/main.tf
Per b/355941670
Associate workflow w/dedicated SA that can write logs
**Readiness**
- [ x] Yes, **merge** this PR after it is approved
**Style**
- [x ] My sample follows the rules described for Terraform in the [Effective Samples style guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [ x] My sample follows the other requirements and best practices in the [Contributing
**Testing**
- [x ] I have performed tests described in the [Contributing guide](https://github.com/terraform-google-modules/terraform-docs-s …
=> docs: Update main.tf to support how-to guide in Eventarc docset

gke/autopilot/mesh/main.tf, gke/enterprise/mesh/main.tf
Adds cluster and fleet (enterprise) mesh samples
b/387532163
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/service-mesh/docs/onboarding/provision-control-plane
Reason:
**Review**
=> feat(gke): add mesh samples

gke/autopilot/policycontroller/main.tf, gke/enterprise/policycontroller/main.tf
b/388331591
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/enterprise/policy-controller/docs/how-to/installing-policy-controller
Reason:
**Review**
=> feat(gke): add policycontroller samples

gke/enterprise/config_sync/git/main.tf, gke/enterprise/config_sync/git/test.yaml, gke/enterprise/config_sync/oci/main.tf, gke/enterprise/config_sync/oci/test.yaml
b/388321419
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/enterprise/config-sync/docs/how-to/installing-config-sync
Reason:
**Review**
=> feat(gke): add config_sync (fleet) example

network_management/vpcflowlogs/interconnect_attachment_basic/main.tf, network_management/vpcflowlogs/interconnect_attachment_full/main.tf, network_management/vpcflowlogs/vpn_tunnel_basic/main.tf, network_management/vpcflowlogs/vpn_tunnel_full/main.tf
Terraform API for VPC Flow Logs is now GA and beta tags can be removed.
Fixes # 389166580
**Readiness**
**Style**
**Testing**
Location(s): [https://cloud.google.com/vpc/docs/using-flow-logs](https://cloud.google.com/vpc/docs/using-flow-logs#enable-vlan-attachment)
Reason:
**Review**
=> feat: Remove "provider = google-beta" tag from examples from VPC Flow Logs.

gke/standard/regional/node_system_config/main.tf
b/389592650
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/docs/how-to/node-system-config
Reason:
**Review**
=> feat(gke): add node system config

network_security/mirroring/basic/consumer/main.tf, network_security/mirroring/basic/producer/main.tf
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/network-security-integration/docs/out-of-band/out-of-band-integration-overview
Reason:
Already done in a separate PR.
**Review**
Already done in a separate PR.
=> feat(networksecurity): add tags for all resources in Mirroring docs

cloud_sql/sqlserver_instance_pitr/main.tf
Add PITR Terraform code samples for Cloud SQL for SQL Server.
Fixes #b/388607470
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
=> feat(cloud_sql): Add Cloud SQL Server PITR

media_cdn/dynamic_compression/main.tf, media_cdn/dynamic_compression/test.yaml
Fixes #b/399751161
**Readiness**
**Style**
**Testing**
Note: I tested with Cloud Shell in my own project.
Location(s):
Reason:
- [N/A] If the sample needs an API enabled to pass testing, I have added the service to the [Test setup file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/test/setup/main.tf)
**Review**
- [N/A] If this sample adds a new directory, I have added codeowners to the [CODEOWNERS file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/.github/CODEOWNERS)
=> feat: add media_cdn dynamic_compression sample

privateca/quickstart/main.tf
Fixes # b/399335799
**Readiness**
- [] No, don't **merge** this PR after it is approved
**Style**
**Testing**
Location(s): https://cloud.google.com/certificate-authority-service/docs/using-terraform#tf-config-sample
Reason:
**Review**
=> Update code sample to use a sub-CA to issue leaf certificates

gke/standard/zonal/no-channel-to-release-channel/main.tf
Fixes # b/396134995
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/docs/how-to/release-channels
Reason:
**Review**
=> feat: Add no channel to release channel samples for GKE

.github/CODEOWNERS
As a prerequisite for adding doc samples under `networksecurity/intercept`, setting the `pm2-team` group as owners.
The members of this team are the owners for Network Security Integration product which includes both intercept and mirroring.
For reference, this is the PR that added mirroring: https://github.com/terraform-google-modules/terraform-docs-samples/pull/806
**Readiness**
=> feat: pre configure networksecurity/intercept samples

network_security/intercept/basic/consumer/main.tf, network_security/intercept/basic/producer/main.tf
Fixes #405705397
Adding samples for creating a simple consumer and producer setup of Network Security In-band Integration using the intercept Terraform resources.
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/network-security-integration/docs/in-band/in-band-integration-overview
Reason:
**Review**
=> feat(networksecurity): Add examples for creating consumer and producer intercept

eventarc/use_cmek/main.tf
Fixes b/404495162 
Enable CMEK support for Eventarc through Terraform
**Readiness**
- [ x] Yes, **merge** this PR after it is approved
**Style**
- [ x] My sample follows the rules described for Terraform in the [Effective Samples style guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [x ] My sample follows the other requirements and best practices in the [Contributing
**Testing**
- [x ] I have performed tests described in the [Contributing guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTR …
=> docs: Add CMEK for Eventarc

gke/standard/zonal/secondary-boot-disk/main.tf
Addresses periodic failures (https://github.com/terraform-google-modules/terraform-docs-samples/issues/781#issuecomment-2764648219) `Error 400: No valid versions with the prefix "1.28" found.`
Removes `min_master_version`
The default version should be >1.28 for all release channels apart from Extended ([source](https://cloud.google.com/kubernetes-engine/docs/release-notes)).  Logged upstream  https://github.com/hashicorp/terraform-provider-google/issues/22167
**Readiness**
=> fix: unset min_master_version (outdated for all channels except EXTENDED)

network_security/mirroring/basic/consumer/main.tf, network_security/mirroring/basic/producer/main.tf
Use the google provider (implicitly the default) instead of the google-beta provider for mirroring samples.
This will fix our docs that currently show the google-beta provider in their terraform samples.
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
=> feat(networksecurity): Remove google-beta provider from mirroring samples

run/custom_domain_mapping/main.tf
Fixes [b/372570764](http://b/372570764)
Changes in documentation: [cl/742799018](http://cl/742799018)
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/run/docs/mapping-custom-domains#map
Reason:
**Review**
=> docs: clarify placeholder values in custom_domain_mapping example

.github/CODEOWNERS
Adding `cloudsql-connectivity` team as owner of `cloud_sql` folder for reviewing updates to cloud sql terraform script samples.
**Readiness**
=> feat: adding cloudsql-connectivity team as owner of cloud_sql folder

network_security/intercept/basic/consumer/main.tf, network_security/intercept/basic/consumer/test.yaml
Adding samples for Security Profile, Security Profile Group and Global Firewall Policy, to showcase how an "apply_security_profile_group" rule is added.
CI tests are skipped since there are permission issues with org/folder level resources.
Local testing was performed successfully.
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
=> feat(networksecurity): Add samples for intercept firewall rule creation

network_security/mirroring/basic/consumer/main.tf, network_security/mirroring/basic/consumer/test.yaml
Adding samples for Security Profile, Security Profile Group and Global Firewall Policy, to showcase how a mirroring rule is added.
CI tests are skipped since there are permission issues with org/folder level resources.
Local testing was performed successfully.
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
=> feat(networksecurity): Add samples for mirroring rule creation

cloud_sql/mysql_instance_psa_psc/main.tf, cloud_sql/postgres_instance_psa_psc/main.tf, cloud_sql/sqlserver_instance_psa_psc/main.tf
Fixes #383556956
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/sql/docs/mysql/configure-private-services-access-and-private-service-connect#terraform
Reason:
**Review**
=> feat(cloud_sql): add disabling psc on PSA+PSC instances examples

gke/standard/regional/hpa-logs/main.tf
Fixes b/394358327
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/docs/how-to/view-horizontalpodautoscaling-events
Reason:
**Review**
=> feat(GKE): add hpa_logs

build/int.cloudbuild.yaml, gke/autopilot/basic/main.tf, gke/autopilot/config_sync/git/main.tf, gke/autopilot/config_sync/oci/main.tf, gke/autopilot/iap/main.tf, gke/autopilot/labels/main.tf, gke/autopilot/mesh/main.tf, gke/autopilot/policycontroller/main.tf, gke/autopilot/release_channel/main.tf, gke/autopilot/reservation/main.tf, gke/autopilot/tag/main.tf, gke/standard/regional/binary-authorization/main.tf, gke/standard/regional/gemma-tgi/main.tf, gke/standard/regional/hpa-logs/main.tf, gke/standard/regional/labels/main.tf, gke/standard/regional/loadbalancer/main.tf, gke/standard/regional/multi-zone/main.tf, gke/standard/regional/node_pool/main.tf, gke/standard/regional/node_system_config/main.tf, gke/standard/regional/single-zone/main.tf, gke/standard/regional/windows/main.tf, gke/standard/zonal/arm/main.tf, gke/standard/zonal/gpu/main.tf, gke/standard/zonal/multi-zone/main.tf, gke/standard/zonal/node_image/main.tf, gke/standard/zonal/reservation/main.tf, gke/standard/zonal/secondary-boot-disk/main.tf, gke/standard/zonal/single-zone/main.tf
Fixes b/401371689
- add hcledit step for tf resource fixup
- migrate `deletion_protection = false` for non-quickstart google_container_cluster.default
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
=> chore: add hcledit for tf resource fixup

build/int.cloudbuild.yaml
Borrowed from python-docs-samples https://github.com/GoogleCloudPlatform/python-docs-samples/blob/a163a4247af1ccdcb6138756e0adf75604069326/.kokoro/tests/run_tests.sh#L35
Should ensure that changes to CODEOWNERS only in .github (and other meta config files) don't fire all tests (blocks new sample onboarding)
=> chore(ci): adjust validation of test changes

network_security/intercept/basic/consumer/main.tf, network_security/intercept/basic/producer/main.tf
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
=> feat(networksecurity): Use google provider for intercept samples.

backupdr/backup_plan/main.tf, backupdr/backup_plan/test.yaml, backupdr/backup_plan_association/main.tf, backupdr/backup_plan_association/test.yaml
**Readiness**
-  [x] Yes, **merge** this PR after it is approved
**Style**
**Testing**
Location(s): https://cloud.devsite.corp.google.com/backup-disaster-recovery/docs/cloud-console/compute/disk-backup#configure_a_scheduled_backup
Reason:
**Review**
=> feat(backupdr): Add disks example code for backup-plan and backup-plan-association

looker/looker-core-psc/main.tf, looker/looker-core-psc/test.yaml
Fixes b/429215192
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
=> feat: Add TF samples for creating a Looker (Google Cloud core) Enterprise instance that uses PSC
