- cloud_run_service_pubsub/main.tf
> add required project argument in resource

- vertex_ai_dataset/main.tf
https://cloud.google.com/vertex-ai/docs/datasets/create-dataset-ap
```release-note:none
```
> Prepared vertex_ai_dataset for inclusion in C.G.C documentation

- flask_google_cloud_quickstart/main.tf
Intended as update to this page:
https://cloud.google.com/docs/terraform/get-started-with-terraform
> Added VPC resources to Flask VM example

- regional-external-http-load-balancer/main.tf
Fixing this issue:
https://github.com/terraform-google-modules/terraform-docs-samples/issues/170
> Fixed forwarding rule region

- cloud_run_service_connect_cloud_sql/main.tf
Intended snippets to add to documentation: https://cloud.google.com/sql/docs/mysql/connect-run
> Add snippets to connect cloud sql to cloud run service instance

- cloudfunctions2_basic_auditlogs/test.yaml
- cloudfunctions2_basic_gcs/test.yaml
- vertex_ai_dataset/test.yaml
Will open P1 bugs for sample owners to retest in new projects and fix anything that's fixable.
> Added skip tests for consistently failing samples

- vertex_ai_metadata_store/main.tf
Attempting to fix error:
Error 409: Requested entity already exists
> vertex_ai_metadata_store/main.tf

- cloudfunctions2_basic_auditlogs/main.tf
- cloudfunctions2_basic_gcs/main.tf
- dns_managed_zone_basic/main.tf
- dns_managed_zone_private/main.tf
- dns_managed_zone_private_forwarding/main.tf
- dns_managed_zone_private_peering/main.tf
- dns_managed_zone_service_directory/main.tf
- dns_policy_basic/main.tf
- dns_record_set_basic/main.tf
- dns_response_policy_basic/main.tf
- dns_response_policy_rule_basic/main.tf
- eventarc_basic_tf/main.tf
- internal_http_lb_with_mig_backend/main.tf
- network_management_connectivity_test_addresses/main.tf
- network_management_connectivity_test_instances/main.tf
- os_login/main.tf
- privateca_certificate_authority_subordinate/main.tf
- privateca_certificate_config/main.tf
- privateca_certificate_csr/main.tf
- privateca_certificate_with_template/main.tf
- privateca_quickstart/main.tf
- shared_vpc_http_ilb_with_mig_backend_basic_example/main.tf
- shared_vpc_http_ilb_with_mig_backend_cross_reference_example/main.tf
- shared_vpc_https_ilb_with_mig_backend_basic_example/main.tf
- shared_vpc_https_ilb_with_mig_backend_cross_reference_example/main.tf
- url_map_header_based_routing/main.tf
- url_map_parameter_based_routing/main.tf
Fix for https://github.com/terraform-google-modules/terraform-docs-samples/issues/146
> Removed dashes from any resources names and replaced with _

- autoscaler_instance_group.tf
- autoscaler_instance_group/main.tf
Planning to use on this page:
https://cloud.google.com/compute/docs/autoscaler/scaling-schedules#creating_a_scaling_schedule
> Added autoscaler example with schedule

- autoscaler_instance_group.tf
- autoscaler_instance_group/main.tf
Sample to live here:
https://cloud.google.com/compute/docs/autoscaler/scaling-schedules
> Removed irrelevant config from autoscaler schedule sample and other minor cleanup

- shared_vpc_http_ilb_with_mig_backend_basic_example/main.tf
- shared_vpc_http_ilb_with_mig_backend_cross_reference_example/main.tf
- shared_vpc_https_ilb_with_mig_backend_basic_example/main.tf
- shared_vpc_https_ilb_with_mig_backend_cross_reference_example/main.tf
Update project names as per https://github.com/hashicorp/terraform-provider-google/pull/12846
Check http://b/256705397 for more details
> Update project names

- compute_disk/main.tf
Intending to use on these pages:
https://cloud.google.com/compute/docs/disks/create-disk-from-source
https://cloud.google.com/compute/docs/disks/create-snapshots
https://cloud.google.com/compute/docs/disks/regional-persistent-disk
> Added compute disk example

- compute_disk/main.tf
For this page:
https://cloud.google.com/compute/docs/disks/create-disk-from-source
> Added parent region tag to group two resources together

- test/integration/sample_test.go
This modifies test discovery to allowing samples to be discovered from any nested dirs by recursively walking directories containing .tf files.
> chore: flexible test discovery

- cloud_run_system_packages/main.tf
Tutorials are being updated to use custom service accounts with minimal permissions. This PR shows that via terraform.
> feature: minimize permissions for system pkgs example

- eventarc_workflows/main.tf
- eventarc_workflows/workflow.tftpl
https://cloud.google.com/eventarc/docs/creating-triggers-terraform
```release-note:none
```
> Updated the comment about the workflow.tftpl file

- dns_managed_zone_reverse_lookup/main.tf
Add example for DNS reverse lookup
Example reference - https://cloud.google.com/dns/docs/zones/managed-reverse-lookup-zones#console
> chore(dns): example cloud dns reverse lookup

- dns_policy_inbound/main.tf
- dns_policy_outbound/main.tf
add dns policy examples for inbound and outbound
> chore(dns): add dns policy examples

- compute_packet_mirroring_full/main.tf
Planning to use here:
https://cloud.google.com/vpc/docs/using-packet-mirroring#terraform
> Fixed dupe region tags

- dns_managed_zone_with_wildcard_certificate/main.tf
- dns_managed_zone_with_wildcard_certificate/terraform.tfvars
add dns_managed_zone_with_wildcard_certificate sample
> dns_managed_zone_with_wildcard_certificate sample

- dns_managed_zone_with_wildcard_certificate/main.tf
Planning to add sample here:
https://cloud.google.com/certificate-manager/docs/dns-authorizations
> Added region tags

- cloud_run_service_ingress/main.tf
- cloud_run_service_static_outbound/main.tf
**Issue:** Workaround to resolve failing tests `TestSamples/3/cloud_run_service_ingress`, `TestSamples/3/cloud_run_service_static_outbound` by adding lifecycle rule for both samples to ignore changes.
> fix(tests): adding lifecycle rule to ignore changes

- cloud_run_healthchecks_startup_probe_http/main.tf
**Issue:** Removing no longer necessary metadata related to launch stage (CL 497285032)
> chore(healthchecks): removing beta launch stage metadata

- compute/basic_vm/main.tf
Intending to include on https://cloud.google.com/compute/docs/instances/create-start-instance
> TF for Compute: instances/create-start-instance 

- cloud_run_healthchecks_startup_probe_http/main.tf
- compute/basic_vm/main.tf
Intending to use here:
https://cloud..google.com/compute/docs/instances/create-start-instance
> Updated image and comment

- CONTRIBUTING.md
Formatted test environment section as steps and added info about getting the org, folder, and billing IDs
> CONTRIBUTING: Added info about getting the org, folder, and billing IDs

- cloud_run_service_multiple_regions/main.tf
> fix: removing properties from cloud run multiple regions

- cloud_run_jobs_create/main.tf
- cloud_run_jobs_execute_jobs_on_schedule/main.tf
- cloud_run_jobs_max_retries_create/main.tf
- cloud_run_jobs_task_parallelism_create/main.tf
- cloud_run_jobs_task_timeout_create/main.tf
**Issue:** Samples to be added to the following documentation
* https://cloud.google.com/run/docs/create-jobs
* https://cloud.google.com/run/docs/execute/jobs
* https://cloud.google.com/run/docs/execute/jobs-on-schedule
* https://cloud.google.com/run/docs/configuring/max-retries
* https://cloud.google.com/run/docs/configuring/task-timeout
* https://cloud.google.com/run/docs/configuring/parallelism
> feat(jobs): initial set of samples for jobs

- cloud_run_jobs_execute_jobs_on_schedule/main.tf
> fix(scheduler-job): service account update for cloud_run_jobs_execute_jobs_on_schedule

- CONTRIBUTING.md
This PR will add the following to `CONTRIBUTING.md`:
- Link to Contributor License Agreement
- Link to Community Guidelines
> Updates to `CONTRIBUTING.md`

- compute/basic_vm_custom_subnet/main.tf
- compute/basic_vm_default_network/main.tf
- compute/compute_disk/main.tf
- compute/instance_custom_hostname/main.tf
- compute/region_autoscaler_basic/main.tf
After these are merged, I will update the following files to point to them. Then I'll delete the old samples on GitHub.
https://cloud.google.com/compute/docs/disks/create-snapshots
https://cloud.google.com/compute/docs/instance-templates/create-instance-templates
https://cloud.google.com/compute/docs/instances/create-start-instance
https://cloud.google.com/compute/docs/instances/custom-hostname-vm
> changing region tags to work with sample browser

- test/setup/main.tf
> chore: fix invalid API

- CONTRIBUTING.md
- README.md
Updated README to point to the new style guidelines and the contributing guide
Moved remaining style guidelines to Contributing guide
> Add content contributing and added links to README

- .github/pull_request_template.md
Fixed some formatting issues in the PR template
Added a checkbox to Contributing in the style section.
> Formatting update

- vertex_ai/dataset/main.tf
- vertex_ai/endpoint/main.tf
- vertex_ai/featurestore/main.tf
- vertex_ai/featurestore_entitytype/main.tf
- vertex_ai/index/main.tf
- vertex_ai/managed_notebooks_runtime/main.tf
- vertex_ai/metadata_store/main.tf
- vertex_ai/tensorboard/main.tf
- vertex_ai/user_managed_notebooks_instance/main.tf
1. Remove API enabling steps from the samples.  API enabling is done outside of the samples
2. Update providers as some resources have been promoted from beta to GA
3. Update some fields based on user feedback
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
> chore: vertex_ai samples cleanup

- compute_add_persistent_disk/main.tf
Old PR: https://github.com/terraform-google-modules/terraform-docs-samples/blob/c096316386cf212f717c19d2cc38b0ff3c01b91f/compute_add_persistent_disk/main.tf#L33-L56
On a later date, we will move this sample `compute/`
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
> fix: Restoring recently deleted file

- media_cdn/keyset/main.tf
- media_cdn/keyset/test.yaml
- media_cdn/quickstart/main.tf
- media_cdn/quickstart/test.yaml
- media_cdn/security_policies/main.tf
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
> Undoing accidental delete

- media_cdn/keyset/main.tf
- media_cdn/keyset/test.yaml
- media_cdn/quickstart/main.tf
- media_cdn/quickstart/test.yaml
- media_cdn/security_policies/main.tf
- privateca/capool_all_fields/main.tf
- privateca/capool_basic/main.tf
- privateca/certificate_authority_basic/main.tf
- privateca/certificate_authority_byo_key/main.tf
- privateca/certificate_authority_byo_key/test.yaml
- privateca/certificate_authority_subordinate/main.tf
- privateca/certificate_config/main.tf
- privateca/certificate_csr/main.tf
- privateca/certificate_no_authority/main.tf
- privateca/certificate_with_template/main.tf
- privateca/quickstart/main.tf
- privateca/quickstart/test.yaml
readding accidentally deleted privateca samples
> Undo delete

- dns/managed_zone_reverse_lookup/main.tf
- dns/policy_inbound/main.tf
- dns/policy_outbound/main.tf
Some DNS files didn't get moved to new location, and then they were deleted in the old location.
> Added files that didn't get moved before being deleted

- .github/workflows/lint.yaml
switches lint workflow to use GHA
> chore: switch lint to GHA

- bigquery/bigquery_create_dataset_iam/main.tf
- bigquery/bigquery_create_dataset_iam/test.yaml
Fixes #269177646
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/bigquery/docs/datasets
Reason:
**Review**
> feat(bigquery): Add example for creating a dataset and granting access

- certificate_manager/google_managed_lb_auth/main.tf
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
> docs: fix certificate manager mis-match region tag

- compute/add_persistent_disk/main.tf
- compute/autoscaler_instance_group/main.tf
- compute/basic_vm/main.tf
- compute/disk/main.tf
- compute/external_address/main.tf
- compute/os_login_ssh_key/main.tf
- compute/region_autoscaler_basic/main.tf
- compute/run_shutdown_scripts/main.tf
- compute/service_account_for_instances/main.tf
Fixes # b/284476524
**Readiness**
> docs: added parent region tags for Compute samples

- certificate_manager/dns_managed_zone_with_wildcard_certificate/main.tf
- certificate_manager/google_managed_cert/main.tf
- certificate_manager/google_managed_lb_auth/main.tf
Fixes (starts to fix it) #b/284476524
**Readiness**
> docs: added parent tags for Certificate Manager samples

- lb/external_cdn_lb_with_backend_bucket/main.tf
- lb/external_http_lb_bucket_backend/main.tf
- lb/external_http_lb_mig_backend/main.tf
- media_cdn/quickstart/main.tf
- media_cdn/ssl_certificates/main.tf
- storage/flask_google_cloud_quickstart/main.tf
- storage/make_data_public/main.tf
- storage/new_bucket/main.tf
- storage/static_website/main.tf
Add region tags to the main.tf files to make the sample viewable in the sample browser.
**Readiness**
> docs: add parent region tags for Storage, LB & Media CDN

- cloud_sql/mysql_database_basic/main.tf
- cloud_sql/mysql_database_instance/main.tf
- cloud_sql/mysql_instance_cmek/main.tf
- cloud_sql/mysql_instance_ha/main.tf
- cloud_sql/mysql_instance_labels/main.tf
- cloud_sql/mysql_instance_pitr/main.tf
- cloud_sql/mysql_instance_ssl_cert/main.tf
- cloud_sql/postgres_database_basic/main.tf
- cloud_sql/postgres_database_instance/main.tf
- cloud_sql/postgres_instance_cmek/main.tf
- cloud_sql/postgres_instance_ha/main.tf
- cloud_sql/postgres_instance_labels/main.tf
- cloud_sql/postgres_instance_pitr/main.tf
- cloud_sql/postgres_instance_ssl_cert/main.tf
- cloud_sql/sqlserver_database_basic/main.tf
- cloud_sql/sqlserver_database_instance/main.tf
- cloud_sql/sqlserver_instance_cmek/main.tf
- cloud_sql/sqlserver_instance_ha/main.tf
- cloud_sql/sqlserver_instance_labels/main.tf
- cloud_sql/sqlserver_instance_ssl_cert/main.tf
Fixes # [modules/terraform-docs-samples/issues/440](https://github.com/terraform-google-modules/terraform-docs-samples/issues/440)
**Readiness**
> chore(cloudsql): split up Cloud SQL samples

- bigquery/bigquery_create_table/main.tf
- bigquery/bigquery_create_table_cmek/main.tf
- bigquery/bigquery_create_table_cmek/test.yaml
- bigquery/bigquery_create_table_iam/main.tf
- bigquery/bigquery_create_table_iam/test.yaml
Fixes #269181465
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
- [] If the sample needs an API enabled to pass testing, I have added the service to the [Test setup file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/test/setup/main.tf)
**Review**
- [] If this sample adds a new directory, I have added codeowners to the [CODEOWNERS file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/.github/CODEOWNERS)
> feat(bigquery): Add examples for creating a table

- run/connect_cloud_sql/main.tf
Ref cl/551695341
* Test in #464 shows this should run green (IAM changes since #168 (?))
* Introduce new region tag so secrets can be excluded when first referenced in guide
* rename resource id to use 'default', as service is used in postgres/mssql docs.
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
> fix: update Cloud SQL-Cloud Run integration to included config

- compute/os_config_policy/main.tf
- network_management/ipv6_dual_stack/main.tf
Please enter the commit message for your changes. Lines starting
Fixes #146
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
> chore: update resurce name('-' to '_')

- bigquery/biglake/bigquery_create_object_table/main.tf
update: Change "main" to "default"
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/bigquery/docs/object-tables#create-object-table
Reason:
**Review**
> chore(bigquery): update project name "main" to "default" in object table example

- compute/os_config_policy/main.tf
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
> chore(compute): Update description for the OS policy assignment tf sample

- bigquery/bigquery_create_table_ingestion_partitioned/main.tf
- bigquery/bigquery_create_table_partitioned/main.tf
- bigquery/bigquery_create_table_range_partitioned/main.tf
Fixes #269185755
**Readiness**
**Style**
**Testing**
- [X ] **[Lint](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#linting-and-formatting)** pass: `terraform fmt` check
Location(s): https://cloud.google.com/bigquery/docs/creating-partitioned-tables
Reason:
**Review**
> feat(bigquery): Add examples for creating a partitioned table

- bigquery/bigquery_create_table_clustered/main.tf
Fixes #269186184
**Readiness**
**Style**
**Testing**
- [X Yes, this sample will be (or already is) included on cloud.google.com
Location(s): https://cloud.google.com/bigquery/docs/creating-clustered-tables
Reason:
**Review**
> feat(bigquery): Add examples for creating a clustered table

- run/tasks/main.tf
Fixes 319905157
**Readiness**
**Style**
> fix: apply style guide to run/tasks

- CONTRIBUTING.md
Fixes #501
Adds explanation of how to get the sample name, based on sample infra code. 
Additionally updates example test output to use a current sample name. 
**Readiness**
> docs: update CONTRIBUTION to explain how to determine SAMPLE argument

- bigquery/bigquery_create_view/main.tf
Fixes #269188487
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/bigquery/docs/views#creating_a_view
Reason:
**Review**
> feat(bigquery): Add examples for creating a view

- bigquery/bigquery_create_materialized_view/main.tf
- bigquery/bigquery_create_materialized_view/test.yaml
Fixes #269188404
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/bigquery/docs/materialized-views-create
Reason:
**Review**
> feat(bigquery): Add example for creating a materialized view

- cloud_sql/mysql_instance_iam_db_auth/main.tf
- cloud_sql/mysql_instance_iam_db_auth/test.yaml
- cloud_sql/postgres_instance_iam_db_auth/main.tf
- cloud_sql/postgres_instance_iam_db_auth/test.yaml
Adds IAM db auth samples for Cloud SQL MySQL and Postgers
**Readiness**
- [ X  ] Yes, **merge** this PR after it is approved
**Style**
- [ X ] My sample follows the rules described for Terraform in the [Effective Samples style guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [ X ] My sample follows the other requirements and best practices in the [Contributing
**Testing**
- [ X ] I have performed tests described in the [Contributing guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING …
> feat: Add IAM db authentication samples for MySQL and Postgres

- vertex_ai/workbench/main.tf
- vertex_ai/workbench_create_metadata/main.tf
- vertex_ai/workbench_dataproc/main.tf
- vertex_ai/workbench_idle_shutdown/main.tf
- vertex_ai/workbench_remove_metadata/main.tf
- vertex_ai/workbench_update_metadata/main.tf
**Readiness**
- [*] Yes, **merge** this PR after it is approved
**Style**
- [*] My sample follows the rules described for Terraform in the [Effective Samples style guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [*] My sample follows the other requirements and best practices in the [Contributing
**Testing**
- [*] I have performed tests described in the [Contributing guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md):
- [*] …
> feat: Add examples for updating metadata based features on workbench instances.

- compute/zonal_mig_paginated_instances_result/main.tf
Fixes b/216660269
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/compute/docs/instance-groups/add-remove-vms-in-mig#gcloud_5
Reason:
**Review**
> feat: Add example for creating MIG with PAGINATED list managed instances result

- compute/instance_template_preemptible/main.tf
Fixes b/216660863
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/compute/docs/instance-groups/create-mig-with-preemptible-vms#gcloud
- [] No, this sample won't be included on cloud.google.com
Reason:
**Review**
> feat: Add preemptible template example

- bigquery/bigquery_create_reservation/main.tf
- test/setup/main.tf
Fixes #b/269301333
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/bigquery/docs/reservations-get-started#create_a_reservation
Reason:
**Review**
> feat(bigquery): Add example for creating a reservation

- looker/looker_instance_basic/test.yaml
- looker/looker_instance_full/test.yaml
Fixes #609, #610
**Readiness**
> fix: skip tests on looker samples

- gke/standard/zonal/node_image/main.tf
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/docs/how-to/node-images
Reason:
**Review**
> feat(GKE): add node image example

- gke/standard/zonal/arm/main.tf
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/docs/how-to/create-arm-clusters-nodes
Reason:
**Review**
> feat(GKE): add arm cluster and nodePool examples

- .github/CODEOWNERS
- cloud_scheduler/basic/main.tf
Per b/332716875
**Readiness**
- [ x] Yes, **merge** this PR after it is approved
**Style**
- [x ] My sample follows the rules described for Terraform in the [Effective Samples style guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [x ] My sample follows the other requirements and best practices in the [Contributing
**Testing**
- [x ] I have performed tests described in the [Contributing guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md):
- [x ] …
> docs: Add Cloud Scheduler basic snippet

- gke/standard/regional/node_pool/main.tf
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/docs/how-to/node-pools
Reason:
**Review**
> feat: add GKE regional node_pool sample

- gke/standard/regional/loadbalancer/main.tf
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing
Reason:
**Review**
> feat: add GKE loadbalancer sample

- gke/autopilot/tag/main.tf
- add GKE tag sample
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/docs/how-to/tags
Reason:
**Review**
> feat: add GKE tag sample

- .github/CODEOWNERS
- add /test/ to CODEOWNERS for terraform-samples-git-admins and cft-admins
> chore: add test to CODEOWNERS

- gke/standard/regional/windows/main.tf
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/docs/how-to/creating-a-cluster-windows
Reason:
**Review**
> feat(GKE): add windows node pool

- .github/CODEOWNERS
Match `/build/` to `/test/` CODEOWNERS
> chore(CI): update CODEOWNERS

- gke/standard/regional/windows/main.tf
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
> fix: add consolidated gke_standard_regional_windows region tag

- application_integration/main.tf
- test/setup/main.tf
Fixes : b/332222808
**Readiness**
- [* ] Yes, **merge** this PR after it is approved
**Style**
- [ *] My sample follows the rules described for Terraform in the [Effective Samples style guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [* ] My sample follows the other requirements and best practices in the [Contributing
**Testing**
- [* ] I have performed tests described in the [Contributing guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md):
- [ *] …
> feat(application integration): Add example for editing region

- gke/quickstart/autopilot/app.tf
- gke/quickstart/autopilot/cluster.tf
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
> fix(GKE): add comment on how to use an external IPV6

- gke/standard/zonal/gpu/main.tf
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/docs/how-to/gpus-multi
Reason:
**Review**
> feat(GKE): add gpu cluster

- compute/region_autoscaler_basic/main.tf
Changed the service account scope in the sample.
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
> fix(compute): Changed the service account scope in the sample

- gke/standard/zonal/gpu/main.tf
- update machine and gpu type in existing sample
**Readiness**
**Style**
**Testing**
Location(s):existing
Reason:
**Review**
> chore(GKE): switch gpu example type

- compute/quickstart/create_vm/main.tf
- compute/terraform_quickstart/create_vm/main.tf
I intend to use this sample in a new Terraforn quickstart that I'm creating in https://cloud.google.com/docs/terraform/
**Readiness**
**Style**
**Testing**
- [X ] **[Tests](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#set-up-the-test-environment)** pass: `terraform apply`
- [ X] **[Lint](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#linting-and-formatting)** pass: `terraform fmt` check
- [ X] Yes, this sample …
> feat: Prepared Terraform quickstart sample for inclusion in C.G.C documentation

- test/setup/main.tf
- Enable for upcoming PRs (https://github.com/terraform-google-modules/terraform-docs-samples/pull/633)
> chore(CI): enable gkee apis

- test/setup/main.tf
Prerequisite for https://github.com/terraform-google-modules/terraform-docs-samples/pull/633
> chore(CI): add connectgateway.googleapis.com

- gke/quickstart/multitenant/backend.yaml
- gke/quickstart/multitenant/frontend.yaml
- gke/quickstart/multitenant/main.tf
- main.tf - code snippet Terraform to build out a multitenant GKE cluster and shared database
- frontend.yaml - frontend-team sample app to apply with kubectl
- backend.yaml - backend-team sample app to apply with kubectl
**Readiness**
**Style**
**Testing**
Location(s):
- New GKEE Multitenant Quickstart
Reason:
**Review**
> feat(GKE): add multitenant quickstart

- gke/enterprise/enable/main.tf
- gke/quickstart/multitenant/main.tf
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/enterprise/docs/setup/enable-gkee
Reason:
**Review**
> feat(GKEE): add enable gkee sample

- bigquery/bigquery_create_reservation_none/main.tf
Fixes #332611431
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/bigquery/docs/reservations-assignments#assign-project-to-none
Reason:
**Review**
> feat(bigquery): Add example for creating a none reservation assignment

- test/setup/fixtures.tf
Resolves needed fixture in #631
Based on discussion in https://github.com/terraform-google-modules/terraform-docs-samples/pull/631/files#r1566694394, a new sub pool fixture is required for this sample. 
**Readiness**
> fix: add my-sub-pool to support #631

- backupdr/backup_plan_association/main.tf
Fixes tail issue in [#761](https://github.com/terraform-google-modules/terraform-docs-samples/pull/761#issuecomment-2489853231)
**Readiness**
**Style**
> fix(backupdr): ensure service account id is long enough

- compute/rmig_instance_flexibility_policy_without_preferences/main.tf
…rmig without having preferences on instanceSelection
Fixes #333070003
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
> feat(compute): add terraform sample for instanceflexibilitypolicy of rmig without having any preferences on instanceselections

- compute/rmig_instance_flexibility_policy/main.tf
- compute/rmig_instance_flexibility_policy_without_preferences/main.tf
…s folder name
Fixes #333070003
**Readiness**
**Style**
**Testing**
Location(s):
Reason:
**Review**
> feat(compute): modify region tag to make them unique and as similar as folder name

- eventarc/workflows/main.tf
- workflows/basic/main.tf
- workflows/cloud_run_job/main.tf
Fixes https://github.com/terraform-google-modules/terraform-docs-samples/issues/743#issuecomment-2529876949
**Readiness**
**Testing**
> fix: add deletion_protection to google workflow resources

- gke/standard/regional/gemma-tgi/main.tf
b/390654591
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/docs/tutorials/serve-gemma-gpu-tgi
Reason:
**Review**
> feat(gke): add gemma standard cluster

- gke/standard/regional/node_system_config/main.tf
b/389592650
**Readiness**
**Style**
**Testing**
Location(s): https://cloud.google.com/kubernetes-engine/docs/how-to/node-system-config#add
Reason:
**Review**
> feat(GKE): add node_system_config node pool
